trigger:
  - master

stages:
  - stage: Build
    displayName: Build Angular App
    jobs:
      - job: BuildApp
        pool: Onprem-UAT-Agent 
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install -g @angular/cli
              npm ci
            displayName: 'Install dependencies'

          - script: ng build --configuration production
            displayName: 'Build Angular App'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'dist/my-angular-project'
              ArtifactName: 'angular-build'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: Deploy to On-Prem Server
    dependsOn: Build
    jobs:
      - deployment: DeployApp
        displayName: 'Deploy to On-Prem Windows Server'
        environment: 'OnPrem'  # Create this environment in Azure DevOps
        pool:
          name: 'Onprem-UAT-Agent'  # Your self-hosted agent pool name
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: angular-build

                - task: CopyFiles@2
                  inputs:
                    SourceFolder: '$(Pipeline.Workspace)/angular-build'
                    Contents: '**'
                    TargetFolder: 'C:\\inetpub\\wwwroot\\MyAngularApp'  # Adjust as needed
                  displayName: 'Copy files to server path'
                - powershell: |
                    Write-Host "Restarting IIS..."
                    iisreset
                  displayName: 'Restart IIS'